version: '2'
services:
  app:
    build:
      context: ./app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  redis_data:
