version: '3'
# docker-compose run web django-admin.py startproject composeexample .
# docker volumn create pgdata
# docker-compose up --build
# docker-compose run web bash
# -> python manage.py migrate
# -> createsuperuser
services:
  db:
    image: postgres:9
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
#   redis_data:
  pgdata:
